# What this Notebook is about?

This Notebook is part of the Data Science for Management course I'm teaching at the University of Florence (Italy) during 2016/2017 academic year. A companion tutorial for the same course is [Python Course for Data Science](https://github.com/andrgig/Data-Science-for-Management/blob/master/Python%20Course%20for%20Data%20Science.ipynb).

For suggestions you can contact me on [Linkedin](https://it.linkedin.com/in/agigli) or [Twitter](https://twitter.com/andrgig).

*Andrea Gigli, PhD in Applied Statistics, MSc in Big Data Analytics and Social Mining*

---

# What is R

R is a powerful language and environment for doing Data Science (ie machine learning, information retrieval, statistical analysis, optimization and visualization). It is a public domain project (“GNU”) which is similar to the commercial S language, an environment which was developed at Bell Laboratories (formerly AT&T, now Lucent Technologies). 

The main advantages of R are the fact that R is freeware and that there is a lot of help available online thanks to a very active community. It is quite similar to other programming packages such as MatLab (not freeware), but more user-friendly than programming languages such as C++ or Java. 

Along with Python, it is one of the most important tools to know for people working with Data at all levels. 

R can be downloaded for free at http://www.r-project.org/

We'll use extensively RStudio interface, available at http://www.rstudio.org/


R can do many statistical and data analyses thanks to the so-called packages or libraries build by R users community. With the standard installation, most common packages are installed. To get a list of all installed packages, go to the RStudio packages window or type library() in the console window.

In [1]:
library()

There are many more packages available on the R website than those you can see. If you want to install and use a package (for example, the package called “geometry”) you should:

1) first click "install packages" in the packages window and then type geometry, or type install.packages("geometry") in the command window,

2) then check the box in front of geometry in the package window or type library("geometry") in the command window.

In [2]:
install.packages("geometry")

ERROR: Error in contrib.url(repos, "source"): trying to use CRAN without setting a mirror


In [3]:
library("geometry")

ERROR: Error in library("geometry"): there is no package called 'geometry'


It's possible to ask help to R on commands using "help()" or "?"

In [4]:
help(round)
?round
help.search("round")

starting httpd help server ... done


## Working Directory
Your working directory is the folder on your computer in which you are currently working. A working directory is always assumed by R
• New files are created by default in this directory
• Files to be read are expected by default in this directory
• getwd() and setwd() are used to manage the it.
When you ask R to open a certain file, it will look in the working directory for this file, and when you tell R to save a data file or figure, it will save it in the working directory.
Before you start working, please set your working directory to where all your data and script files are or should be stored. Type in the command window:

In [5]:
setwd("directoryname")

ERROR: Error in setwd("directoryname"): cannot change working directory


If you want to know your working directory type

In [6]:
getwd()

[1] "C:/Users/t000524/workspace/Management Data Science Course"

setwd("../../Dati/")# sale 2 livelli, entra in Dati
dir() # elenca files/cartelle
dir.create("tmpLavoro")# crea cartella
setwd("tmpLavoro") # vi entra

source("script.R") esegue il codice R contenuto nel file di
testo "script.R" (che potete editare anche con Notepad).
Questo vi consente di:
◮ spezzare un programma in moduli (script) separati, da
eseguire richiamandoli sequenzialmente;
◮ collocare una funzione che usate ripetutamente in uno
script-libreria personale, da caricare all’occorrenza.
Esempio: inizio di un mio “main script”:
source("00_Parametri.R")
source("00_Input.R")
source("00_CaricamentoDati.R")
source("libUtils.R")
source("libFunz.R")

## R as a calculator
You can use R as a calculator and do both basic mathematical operations...

In [7]:
2+2

[1] 4

In [8]:
4-5

[1] -1

In [9]:
4/5

[1] 0.8

In [10]:
8*9

[1] 72

In [11]:
8^2

[1] 64

In [12]:
exp(2)

[1] 7.389056

In [13]:
log(exp(2))

[1] 2

In [14]:
5%%2

[1] 1

In [15]:
5%/%2

[1] 2

... or more complex ones

In [16]:
log((54*3+2)^2)/4

[1] 2.549933

## Variables 
You can create also variables in R and use them later in your scripts. The sign "<-" is used to assign a value to a variable. Variable types are
- Numeric
- Boolean
- Character

In [17]:
#numeric variable
x <- 10

Afterwards, no result is displayed. To view the content of the variable just call the variable

In [18]:
x

[1] 10

You can also write the assignement operation in brackets

In [19]:
(x <- 20)

[1] 20

In [20]:
y <- x + 10
z <- x^(3/4) -pi*y
z

[1] -84.79036

In [21]:
# boolean variable
z > 0

[1] FALSE

In [22]:
!(z > 0)

[1] TRUE

In [23]:
#string variable
string <- "pippo"
string

[1] "pippo"

In [24]:
boolean <- TRUE
boolean

[1] TRUE

"Inf" and "NaN" stand for Infinite Number and Missing data: 

In [25]:
1/0

[1] Inf

In [26]:
0/0

[1] NaN

In [27]:
10*1/0

[1] Inf

In [28]:
10*0/0

[1] NaN

is.na() can be used to test if a variable has missing value

In [29]:
is.na(0/0)

[1] TRUE

## Dates and Time

The as.Date function is a built-in function able to handle dates (without time, without control zone). The chron library handles dates and times (without control zones). POSIXct and POSIXlt classes allow for dates and times with control for time zones.

### as.Date

The as.Date function allows a variety of input formats through the format = argument. The default format is a four digit year, followed by a month, then a day, separated by either dashes or slashes


In [30]:
as.Date('1915-6-16')

[1] "1915-06-16"

| Code | Value         
| :- |:-------------
| %d | Day of the month (decimal) 
| %m | Month (decimal)
| %b | Month (abbreviated name)
| %B | Month (full name)
| %y | Year (2 digits)
| %Y | Year (4 digits)



In [31]:
as.Date('01/15/2001',format='%m/%d/%Y')

[1] "2001-01-15"

In [32]:
 as.Date('April 26, 2001',format='%B %d, %Y')

[1] "2001-04-26"

**Internally, Date objects are stored as the number of days since January 1, 1970**, using negative numbers for earlier dates. The as.numeric function can be used to convert a Date object to its internal form.

To extract the components of the dates, the weekdays, months, days or quarters functions can be used.

In [33]:
bdays = c(tukey=as.Date('1915-06-16'),fisher=as.Date('1890-02-17'),
          cramer=as.Date('1893-09-25'), kendall=as.Date('1907-09-06'))
weekdays(bdays)
months(bdays)

tukey      fisher      cramer     kendall 
"Wednesday"    "Monday"    "Monday"    "Friday"

tukey      fisher      cramer     kendall 
     "June"  "February" "September" "September"

### chron
This class is a good option when you don’t need to deal with timezones. It requires the package chron.

In [34]:
require(chron)

Loading required package: chron


In [35]:
#create some times:

tm1.c <- as.chron("2013-07-24 23:55:26")
tm1.c

[1] (07/24/13 23:55:26)

In [36]:
attributes(tm1.c)

$format
  dates   times 
"m/d/y" "h:m:s" 

$origin
month   day  year 
    1     1  1970 

$class
[1] "chron" "dates" "times"

In [37]:
tm2.c <- as.chron("07/25/13 08:32:07", "%m/%d/%y %H:%M:%S")
tm2.c

[1] (07/25/13 08:32:07)

In [38]:
#extract just the date:

dates(tm1.c)

    day  
07/24/13 

In [39]:
#compare times:

tm2.c > tm1.c

[1] TRUE

In [40]:
#add days:

tm1.c + 10


[1] (08/03/13 23:55:26)

In [41]:
#calculate the differene between times:
tm2.c - tm1.c

[1] 08:36:41

In [42]:
difftime(tm2.c, tm1.c, units = "hours")
## Time difference of 8.611 hours

Time difference of 8.611389 hours

In [43]:
#does not adjust for daylight savings time:

as.chron("2013-03-10 08:32:07") - as.chron("2013-03-09 23:55:26")


[1] 08:36:41

### POSIXct
This class enables easy extraction of specific componants of a time. (“ct” stand for calender time and “lt” stands for local time. “lt” also helps one remember that POXIXlt objects are lists.)

In [44]:
#Get the current time (in POSIXct by default):

Sys.time()

[1] "2016-12-28 16:43:12 CET"

In [45]:
#create some POSIXct objects:

tm1 <- as.POSIXct("2013-07-24 23:55:26")
tm1

[1] "2013-07-24 23:55:26 CEST"

In [46]:
attributes(tm1)

$class
[1] "POSIXct" "POSIXt" 

$tzone
[1] ""

In [47]:
tm2 <- as.POSIXct("25072013 08:32:07", format = "%d%m%Y %H:%M:%S")
tm2

[1] "2013-07-25 08:32:07 CEST"

In [48]:
#specify the time zone:

tm3 <- as.POSIXct("2010-12-01 11:42:03", tz = "GMT")
tm3

[1] "2010-12-01 11:42:03 GMT"

In [49]:
tm2 > tm1

[1] TRUE

In [50]:
tm2 - tm1

Time difference of 8.611389 hours

In [51]:
tm1
tm1 + 30

[1] "2013-07-24 23:55:26 CEST"

[1] "2013-07-24 23:55:56 CEST"

In [52]:
#automatically adjusts for daylight savings time:

as.POSIXct("2013-03-10 08:32:07") - as.POSIXct("2013-03-09 23:55:26")

Time difference of 8.611389 hours

### POSIXlt
This class enables easy extraction of specific componants of a time. (“ct” stand for calender time and “lt” stands for local time. “lt” also helps one remember that POXIXlt objects are lists.)

In [53]:
#create a time:

tm1.lt <- as.POSIXlt("2013-07-24 23:55:26")
tm1.lt


[1] "2013-07-24 23:55:26 CEST"

In [54]:
attributes(tm1.lt)

$names
 [1] "sec"    "min"    "hour"   "mday"   "mon"    "year"   "wday"   "yday"  
 [9] "isdst"  "zone"   "gmtoff"

$class
[1] "POSIXlt" "POSIXt"

In [55]:
unclass(tm1.lt)

$sec
[1] 26

$min
[1] 55

$hour
[1] 23

$mday
[1] 24

$mon
[1] 6

$year
[1] 113

$wday
[1] 3

$yday
[1] 204

$isdst
[1] 1

$zone
[1] "CEST"

$gmtoff
[1] NA

In [56]:
unlist(tm1.lt)

sec    min   hour   mday    mon   year   wday   yday  isdst   zone gmtoff 
  "26"   "55"   "23"   "24"    "6"  "113"    "3"  "204"    "1" "CEST"     NA

In [57]:
#extract componants of a time object:

tm1.lt$se

[1] 26

In [58]:
#truncate or round off the time:

trunc(tm1.lt, "days")


[1] "2013-07-24 CEST"

In [59]:
trunc(tm1.lt, "mins")

[1] "2013-07-24 23:55:00 CEST"

### Useful Properties

In [60]:
typeof(x)

[1] "double"

In [61]:
typeof(string)

[1] "character"

In [62]:
typeof(boolean)

[1] "logical"

## Vectors and Lists
Vector is the basic data structure in R. It can be atomic vector (all elements are the same type) or list (element can have different type).


In [63]:
#combine objects into an atomic vector
y <- c(1,2,3)

In [64]:
y

[1] 1 2 3

In [65]:
string <- "pippo"
strings <- c(string, "pluto")

In [66]:
strings

[1] "pippo" "pluto"

Atomic vectors are always flat

In [67]:
c(1,c(2, c(3,4)))

[1] 1 2 3 4

In [68]:
v <- vector(10, mode="numeric"); v #initializa a vector of numerics

[1] 0 0 0 0 0 0 0 0 0 0

Vectors can be created via ad'hoc buil-in functions. A very useful function is seq()

In [69]:
seq(from = 1, to = 10, by = 3)

[1]  1  4  7 10

In [70]:
v <- seq(-1,1,0.01)
v

[1] -1.00 -0.99 -0.98 -0.97 -0.96 -0.95 -0.94 -0.93 -0.92 -0.91 -0.90 -0.89
 [13] -0.88 -0.87 -0.86 -0.85 -0.84 -0.83 -0.82 -0.81 -0.80 -0.79 -0.78 -0.77
 [25] -0.76 -0.75 -0.74 -0.73 -0.72 -0.71 -0.70 -0.69 -0.68 -0.67 -0.66 -0.65
 [37] -0.64 -0.63 -0.62 -0.61 -0.60 -0.59 -0.58 -0.57 -0.56 -0.55 -0.54 -0.53
 [49] -0.52 -0.51 -0.50 -0.49 -0.48 -0.47 -0.46 -0.45 -0.44 -0.43 -0.42 -0.41
 [61] -0.40 -0.39 -0.38 -0.37 -0.36 -0.35 -0.34 -0.33 -0.32 -0.31 -0.30 -0.29
 [73] -0.28 -0.27 -0.26 -0.25 -0.24 -0.23 -0.22 -0.21 -0.20 -0.19 -0.18 -0.17
 [85] -0.16 -0.15 -0.14 -0.13 -0.12 -0.11 -0.10 -0.09 -0.08 -0.07 -0.06 -0.05
 [97] -0.04 -0.03 -0.02 -0.01  0.00  0.01  0.02  0.03  0.04  0.05  0.06  0.07
[109]  0.08  0.09  0.10  0.11  0.12  0.13  0.14  0.15  0.16  0.17  0.18  0.19
[121]  0.20  0.21  0.22  0.23  0.24  0.25  0.26  0.27  0.28  0.29  0.30  0.31
[133]  0.32  0.33  0.34  0.35  0.36  0.37  0.38  0.39  0.40  0.41  0.42  0.43
[145]  0.44  0.45  0.46  0.47  0.48  0.49  0.50  0.51  0.52  0.53  0.54  0.55
[157]  0.56  0.57  0.58  0.59  0.60  0.61  0.62  0.63  0.64  0.65  0.66  0.67
[169]  0.68  0.69  0.70  0.71  0.72  0.73  0.74  0.75  0.76  0.77  0.78  0.79
[181]  0.80  0.81  0.82  0.83  0.84  0.85  0.86  0.87  0.88  0.89  0.90  0.91
[193]  0.92  0.93  0.94  0.95  0.96  0.97  0.98  0.99  1.00

Vector elements can be accessed in several ways

In [71]:
v[1]

[1] -1

In [72]:
v[1:3]

[1] -1.00 -0.99 -0.98

In [73]:
v[c(10:12,28:29,32)]

[1] -0.91 -0.90 -0.89 -0.73 -0.72 -0.69

**Be aware R doesn't work like Python**... If you type v[-1] you get the vector without the first elemnt and not the last element of the vector

In [74]:
v[-1]

[1] -0.99 -0.98 -0.97 -0.96 -0.95 -0.94 -0.93 -0.92 -0.91 -0.90 -0.89 -0.88
 [13] -0.87 -0.86 -0.85 -0.84 -0.83 -0.82 -0.81 -0.80 -0.79 -0.78 -0.77 -0.76
 [25] -0.75 -0.74 -0.73 -0.72 -0.71 -0.70 -0.69 -0.68 -0.67 -0.66 -0.65 -0.64
 [37] -0.63 -0.62 -0.61 -0.60 -0.59 -0.58 -0.57 -0.56 -0.55 -0.54 -0.53 -0.52
 [49] -0.51 -0.50 -0.49 -0.48 -0.47 -0.46 -0.45 -0.44 -0.43 -0.42 -0.41 -0.40
 [61] -0.39 -0.38 -0.37 -0.36 -0.35 -0.34 -0.33 -0.32 -0.31 -0.30 -0.29 -0.28
 [73] -0.27 -0.26 -0.25 -0.24 -0.23 -0.22 -0.21 -0.20 -0.19 -0.18 -0.17 -0.16
 [85] -0.15 -0.14 -0.13 -0.12 -0.11 -0.10 -0.09 -0.08 -0.07 -0.06 -0.05 -0.04
 [97] -0.03 -0.02 -0.01  0.00  0.01  0.02  0.03  0.04  0.05  0.06  0.07  0.08
[109]  0.09  0.10  0.11  0.12  0.13  0.14  0.15  0.16  0.17  0.18  0.19  0.20
[121]  0.21  0.22  0.23  0.24  0.25  0.26  0.27  0.28  0.29  0.30  0.31  0.32
[133]  0.33  0.34  0.35  0.36  0.37  0.38  0.39  0.40  0.41  0.42  0.43  0.44
[145]  0.45  0.46  0.47  0.48  0.49  0.50  0.51  0.52  0.53  0.54  0.55  0.56
[157]  0.57  0.58  0.59  0.60  0.61  0.62  0.63  0.64  0.65  0.66  0.67  0.68
[169]  0.69  0.70  0.71  0.72  0.73  0.74  0.75  0.76  0.77  0.78  0.79  0.80
[181]  0.81  0.82  0.83  0.84  0.85  0.86  0.87  0.88  0.89  0.90  0.91  0.92
[193]  0.93  0.94  0.95  0.96  0.97  0.98  0.99  1.00

Here are some useful built-in functions you can apply to a vector

In [75]:
length(v) #lunghezza (numero elementi) del vettore v
min(v) #minimo degli elementi in v
max(v) #massimo degli elementi in v
sum(v) #sommatoria degli elementi in v
prod(v) #produttoria degli elementi in v
sort(v) #ritorna vettore con elementi di v riordinati
head(v,5)  #n valori di testa del vettore v
tail(v,5) #n valori di coda del vettore v

[1] 201

[1] -1

[1] 1

[1] 4.107825e-15

[1] 0

[1] -1.00 -0.99 -0.98 -0.97 -0.96 -0.95 -0.94 -0.93 -0.92 -0.91 -0.90 -0.89
 [13] -0.88 -0.87 -0.86 -0.85 -0.84 -0.83 -0.82 -0.81 -0.80 -0.79 -0.78 -0.77
 [25] -0.76 -0.75 -0.74 -0.73 -0.72 -0.71 -0.70 -0.69 -0.68 -0.67 -0.66 -0.65
 [37] -0.64 -0.63 -0.62 -0.61 -0.60 -0.59 -0.58 -0.57 -0.56 -0.55 -0.54 -0.53
 [49] -0.52 -0.51 -0.50 -0.49 -0.48 -0.47 -0.46 -0.45 -0.44 -0.43 -0.42 -0.41
 [61] -0.40 -0.39 -0.38 -0.37 -0.36 -0.35 -0.34 -0.33 -0.32 -0.31 -0.30 -0.29
 [73] -0.28 -0.27 -0.26 -0.25 -0.24 -0.23 -0.22 -0.21 -0.20 -0.19 -0.18 -0.17
 [85] -0.16 -0.15 -0.14 -0.13 -0.12 -0.11 -0.10 -0.09 -0.08 -0.07 -0.06 -0.05
 [97] -0.04 -0.03 -0.02 -0.01  0.00  0.01  0.02  0.03  0.04  0.05  0.06  0.07
[109]  0.08  0.09  0.10  0.11  0.12  0.13  0.14  0.15  0.16  0.17  0.18  0.19
[121]  0.20  0.21  0.22  0.23  0.24  0.25  0.26  0.27  0.28  0.29  0.30  0.31
[133]  0.32  0.33  0.34  0.35  0.36  0.37  0.38  0.39  0.40  0.41  0.42  0.43
[145]  0.44  0.45  0.46  0.47  0.48  0.49  0.50  0.51  0.52  0.53  0.54  0.55
[157]  0.56  0.57  0.58  0.59  0.60  0.61  0.62  0.63  0.64  0.65  0.66  0.67
[169]  0.68  0.69  0.70  0.71  0.72  0.73  0.74  0.75  0.76  0.77  0.78  0.79
[181]  0.80  0.81  0.82  0.83  0.84  0.85  0.86  0.87  0.88  0.89  0.90  0.91
[193]  0.92  0.93  0.94  0.95  0.96  0.97  0.98  0.99  1.00

[1] -1.00 -0.99 -0.98 -0.97 -0.96

[1] 0.96 0.97 0.98 0.99 1.00

Lists are another very useful data structure in R. They are different wrt Vectors because a list can hold different data types.

In [76]:
#list
x <- list(1:3, "a", c(TRUE, FALSE, TRUE), c(2.3, 5.9))
x

[[1]]
[1] 1 2 3

[[2]]
[1] "a"

[[3]]
[1]  TRUE FALSE  TRUE

[[4]]
[1] 2.3 5.9

In [77]:
x[[4]]
typeof(x[[4]])

[1] 2.3 5.9

[1] "double"

In [78]:
x[4]
typeof(x[4])

[[1]]
[1] 2.3 5.9

[1] "list"

In [79]:
x[[4]][2]
typeof(x[[4]][2])

[1] 5.9

[1] "double"

In [80]:
x[2:4]

[[1]]
[1] "a"

[[2]]
[1]  TRUE FALSE  TRUE

[[3]]
[1] 2.3 5.9

In [81]:
L <- list(name = "Andrea", height = 190.0, married = TRUE, number.children = 0, email = "andrgig@gmail.com")
names(L)

[1] "name"            "height"          "married"         "number.children"
[5] "email"

In [82]:
L[[1]] ; L[[5]]
L$married
L$number.children 

[1] "Andrea"

[1] "andrgig@gmail.com"

[1] TRUE

[1] 0

In [83]:
L$number.children <- 1
L


$name
[1] "Andrea"

$height
[1] 190

$married
[1] TRUE

$number.children
[1] 1

$email
[1] "andrgig@gmail.com"

In [84]:
L<-append(L,list(children.name=c("Arianna")))
L

$name
[1] "Andrea"

$height
[1] 190

$married
[1] TRUE

$number.children
[1] 1

$email
[1] "andrgig@gmail.com"

$children.name
[1] "Arianna"

In [85]:
#lists
l <- list()
l[10] <- "pippo"
l[1] <- 1
l <- append(l, "pluto")
l <- c(l, c(1, 2, 3))
l

[[1]]
[1] 1

[[2]]
NULL

[[3]]
NULL

[[4]]
NULL

[[5]]
NULL

[[6]]
NULL

[[7]]
NULL

[[8]]
NULL

[[9]]
NULL

[[10]]
[1] "pippo"

[[11]]
[1] "pluto"

[[12]]
[1] 1

[[13]]
[1] 2

[[14]]
[1] 3

## Arrays and Matrices
Multi-dimensioanl arrays are atomic vector with an additional attribute, dim(). A special case of array structures are matrices, which are bi-dimensional arrays. Matrices can contain numeric values only.

In [86]:
#arrays
a <- array(c(1,2,3,4,5,6,7,8,9,10), c(2,5))

In [87]:
a

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

In [88]:
nrow(a)
ncol(a)

[1] 2

[1] 5

In [89]:
rownames(a) <- c("A", "B")
colnames(a) <- c("a", "b", "c","d","e")
a

a b c d e 
A 1 3 5 7  9
B 2 4 6 8 10

Accesso ad elementi dell'array tramite []:

In [90]:
a[1]
a[1,1]
a[3]
a[1,2]
a[-1]
a[-c(2,4)]

[1] 1

[1] 1

[1] 3

[1] 3

[1]  2  3  4  5  6  7  8  9 10

[1]  1  3  5  6  7  8  9 10

In [91]:
a1 <- array(seq_len(24), c(2,4,3))
a1
a1[1,1,1]
a1[1,1,3]
a1[2,4,3]

, , 1

     [,1] [,2] [,3] [,4]
[1,]    1    3    5    7
[2,]    2    4    6    8

, , 2

     [,1] [,2] [,3] [,4]
[1,]    9   11   13   15
[2,]   10   12   14   16

, , 3

     [,1] [,2] [,3] [,4]
[1,]   17   19   21   23
[2,]   18   20   22   24

[1] 1

[1] 17

[1] 24

In [92]:
length(a1)

[1] 24

In [93]:
attributes(a1)

$dim
[1] 2 4 3

In [94]:
#transform array into vectors
dim(a1) <- NULL
a1

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24

In [95]:
attributes(a1)

NULL

In [96]:
length(a1)

[1] 24

In [97]:
# Matrix definition requires 2 scalar arguments to specify rows and columns
a <- matrix(1:6, ncol = 3, nrow = 2)
a

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [98]:
#or just one of them
m <- matrix(c(1,2,3,4,5,6,7,8,9,10), ncol = 2) # a matrix is a 2D array
m

[,1] [,2]
[1,] 1     6  
[2,] 2     7  
[3,] 3     8  
[4,] 4     9  
[5,] 5    10

In [99]:
dim(m)

[1] 5 2

In [100]:
#get dimensions and set dim names
ncol(m); nrow(m)

[1] 2

[1] 5

Here are some matrix operations you can try

In [101]:
t(m) #matrice trasposta
n <- m*2/5
m + n #matrice somma (componente per componente)
m * n #matrice prodotto componente per componente!!


[,1] [,2] [,3] [,4] [,5]
[1,] 1    2    3    4     5  
[2,] 6    7    8    9    10

[,1] [,2]
[1,] 1.4   8.4
[2,] 2.8   9.8
[3,] 4.2  11.2
[4,] 5.6  12.6
[5,] 7.0  14.0

[,1] [,2]
[1,]  0.4 14.4
[2,]  1.6 19.6
[3,]  3.6 25.6
[4,]  6.4 32.4
[5,] 10.0 40.0

In [102]:
A <- m %*% t(n); A #prodotto matriciale riga per colonna!!
diag(5:7) #crea matrice 3x3 con 0 fuori dalla diagonale
x <- 1:15; dim(x) <- c(3,5) #converte x in matrice 3x5
eigen(A) #calcola autovalori ed autovettori (A quadrata!)
qr(A) #decomposizione QR
svd(A) #Singular Value Decomposition

[,1] [,2] [,3] [,4] [,5]
[1,] 14.8 17.6 20.4 23.2 26  
[2,] 17.6 21.2 24.8 28.4 32  
[3,] 20.4 24.8 29.2 33.6 38  
[4,] 23.2 28.4 33.6 38.8 44  
[5,] 26.0 32.0 38.0 44.0 50

[,1] [,2] [,3]
[1,] 5    0    0   
[2,] 0    6    0   
[3,] 0    0    7

$values
[1]  1.526902e+02  1.309842e+00 -3.424175e-15 -8.114541e-15 -8.136022e-15

$vectors
           [,1]        [,2]        [,3]          [,4]       [,5]
[1,] -0.3042621 -0.71233741  0.00000000  6.324555e-01  0.0000000
[2,] -0.3707409 -0.40317635 -0.02698067 -6.324555e-01  0.5470576
[3,] -0.4372198 -0.09401529  0.44372691 -3.162278e-01 -0.7093000
[4,] -0.5036986  0.21514578 -0.80651180  7.216450e-16 -0.2225730
[5,] -0.5701775  0.52430684  0.38976556  3.162278e-01  0.3848153

$qr
            [,1]        [,2]          [,3]          [,4]          [,5]
[1,] -46.4671927 -56.6076805 -6.674817e+01 -7.688866e+01 -8.702914e+01
[2,]   0.3787619   0.6086934  1.217387e+00  1.826080e+00  2.434773e+00
[3,]   0.4390194  -0.1498862 -6.301922e-15 -6.669632e-16  3.706437e-15
[4,]   0.4992770  -0.4925889  6.518369e-01  1.737456e-15  5.360213e-16
[5,]   0.5595346  -0.8352916 -3.523443e-02  8.753660e-01 -3.983144e-15

$rank
[1] 2

$qraux
[1] 1.318504e+00 1.192816e+00 1.757540e+00 1.483461e+00 3.983144e-15

$pivot
[1] 1 2 3 4 5

attr(,"class")
[1] "qr"

$d
[1] 1.526902e+02 1.309842e+00 6.355119e-15 2.372550e-15 1.313234e-15

$u
           [,1]        [,2]        [,3]        [,4]       [,5]
[1,] -0.3042621 -0.71233741  0.61211795 -0.10250109  0.1216764
[2,] -0.3707409 -0.40317635 -0.74624939 -0.32576568  0.1923241
[3,] -0.4372198 -0.09401529 -0.15069837  0.86802314 -0.1543562
[4,] -0.5036986  0.21514578  0.09167311 -0.34874488 -0.7549656
[5,] -0.5701775  0.52430684  0.19315670 -0.09101149  0.5953213

$v
           [,1]        [,2]        [,3]         [,4]        [,5]
[1,] -0.3042621 -0.71233741  0.33548899  0.334905904  0.41867072
[2,] -0.3707409 -0.40317635 -0.01704823 -0.770650749 -0.32527954
[3,] -0.4372198 -0.09401529 -0.34047150  0.533736673 -0.63182618
[4,] -0.5036986  0.21514578 -0.60986826 -0.095144714  0.56480809
[5,] -0.5701775  0.52430684  0.63189901 -0.002847113 -0.02637309

Matrix elements can be accessed in different ways

In [103]:
#indexing
A[1]
A[c(1,3)]
A[1, 2]
A[1,]

[1] 14.8

[1] 14.8 20.4

[1] 17.6

[1] 14.8 17.6 20.4 23.2 26.0

To remove all variables from R’s memory, click “clear all” in the workspace window or type

In [104]:
rm(list=ls())

 If you only want to remove the variable a, you can type rm(variable_name)

In [105]:
a <- 5
b <- a
ls()
rm(a)
ls()

[1] "a" "b"

[1] "b"

## Factor Variables
A factor is a vector that can contain only predefined values, and is used to store categorical data. Factors are built on top of integer vectors using two attributes: the class(), “factor”, which makes them behave differently from regular integer vectors, and the levels(), which defines the set of allowed values.

In [106]:
x <- c("female","male","male","female", "female")
x

[1] "female" "male"   "male"   "female" "female"

In [107]:
class(x)

[1] "character"

In [108]:
f <- factor(x)
f
class(f)

[1] female male   male   female female
Levels: female male

[1] "factor"

In [109]:
levels(f)
as.numeric(f)

[1] "female" "male"

[1] 1 2 2 1 1

In [110]:
table(f)

f
female   male 
     3      2 

# Dataframes
Dataframes represets the most famous R data structures. They represents a table, with rows and columns, where
1) One column holds data of the same type ( a vector)
2) Different columns can have different data types. ( a list)
3) Every row in a data frame has a row id.

Rows and columns can be accessed through indexes, which can be numeric or associative
- df[ 1, 2 ]
- df$example_column
- df[ 1:3, 4:5 ]


In [111]:
#data frames
df <- data.frame(x = seq_len(20), y =rnorm(20), z = 2*seq_len(20))

df$x

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20

Data Frames can be analyzed using the following commands
• nrow and ncol
• summary
• head
• str

In [112]:
head(df)

x y           z 
1 1 -0.14628418  2
2 2  0.05325144  4
3 3 -0.94819437  6
4 4 -1.95321281  8
5 5 -0.45413154 10
6 6  0.33389572 12

In [113]:
summary(df)

       x               y                 z       
 Min.   : 1.00   Min.   :-1.9532   Min.   : 2.0  
 1st Qu.: 5.75   1st Qu.:-0.6037   1st Qu.:11.5  
 Median :10.50   Median :-0.2372   Median :21.0  
 Mean   :10.50   Mean   :-0.1921   Mean   :21.0  
 3rd Qu.:15.25   3rd Qu.: 0.3221   3rd Qu.:30.5  
 Max.   :20.00   Max.   : 2.2303   Max.   :40.0  

In [114]:
nrow(df); ncol(df)

[1] 20

[1] 3

In [115]:
str(df)

'data.frame':	20 obs. of  3 variables:
 $ x: int  1 2 3 4 5 6 7 8 9 10 ...
 $ y: num  -0.1463 0.0533 -0.9482 -1.9532 -0.4541 ...
 $ z: num  2 4 6 8 10 12 14 16 18 20 ...


In [116]:
names(df)[1] <- "column1"
df$column1
df$x
df$y

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20

NULL

[1] -0.14628418  0.05325144 -0.94819437 -1.95321281 -0.45413154  0.33389572
 [7] -0.32809396 -0.48890386 -0.38527410  0.12631490  0.31822365  0.63948067
[13]  0.40187661 -0.44545510 -1.24935889  0.08808607  0.91141631 -1.06872109
[19]  2.23029768 -1.47660927

# Dataframe creation

Dataframe can be created by combining individual vectors, other data frames or reading from exterlas cources (files or databases).

- read.table() function reads any file into a data frame and it can control file format like newline, separator , header etc.. (write.table() is the equivalent write operation)
- read.csv() function reads a csv file into a data frame and it is dedicated to the csv pre-defined format (write.csv() is the equivalent write operation)
- Files can be downloaded directly from the web using download.file()
- Raw web pages can be scraped using getURL()


**inserire DB COnnection modulo 2 Renato**

In [117]:
##### working with data frames #####
getwd()
ds <- read.table("foods.csv")
#average length of review text
review.length <- unlist(lapply(as.character(knime.in$"ReviewText"), nchar))

[1] "C:/Users/t000524/workspace/Management Data Science Course"

Warning message in file(file, "rt"):
"cannot open file 'foods.csv': No such file or directory"

ERROR: Error in file(file, "rt"): cannot open the connection


Dataframe can be manipulated Data Frames can be combined with rbind() and cbind()
• Columns can be added by using an associative name and contents
example_df$example_col <- c(1,2,3)
• Most operations on vectors can be done on individual rows or
columns of a data frame
• Data Frames can be merged using a common column with the
merge() function
• A number of built-in data frame examples are available in R

## Dataframe transformations: Sorting, Merging, Binning
Any vector can be sorted using the sort() function. A Data Frame can be sorted according to one or more of its ccolumns using the order() function.

In [118]:
sort(df$y)

[1] -1.95321281 -1.47660927 -1.24935889 -1.06872109 -0.94819437 -0.48890386
 [7] -0.45413154 -0.44545510 -0.38527410 -0.32809396 -0.14628418  0.05325144
[13]  0.08808607  0.12631490  0.31822365  0.33389572  0.40187661  0.63948067
[19]  0.91141631  2.23029768

In [119]:
df[order(df$y) , ]

column1 y           z 
4   4      -1.95321281  8
20 20      -1.47660927 40
15 15      -1.24935889 30
18 18      -1.06872109 36
3   3      -0.94819437  6
8   8      -0.48890386 16
5   5      -0.45413154 10
14 14      -0.44545510 28
9   9      -0.38527410 18
7   7      -0.32809396 14
1   1      -0.14628418  2
2   2       0.05325144  4
16 16       0.08808607 32
10 10       0.12631490 20
11 11       0.31822365 22
6   6       0.33389572 12
13 13       0.40187661 26
12 12       0.63948067 24
17 17       0.91141631 34
19 19       2.23029768 38

In [120]:
df[order(-df$z, df$y),]

column1 y           z 
20 20      -1.47660927 40
19 19       2.23029768 38
18 18      -1.06872109 36
17 17       0.91141631 34
16 16       0.08808607 32
15 15      -1.24935889 30
14 14      -0.44545510 28
13 13       0.40187661 26
12 12       0.63948067 24
11 11       0.31822365 22
10 10       0.12631490 20
9   9      -0.38527410 18
8   8      -0.48890386 16
7   7      -0.32809396 14
6   6       0.33389572 12
5   5      -0.45413154 10
4   4      -1.95321281  8
3   3      -0.94819437  6
2   2       0.05325144  4
1   1      -0.14628418  2

Two Data Frames can be merged using a common column – merge()
• If column names are same, no specification required.
• Used for foreign key operations (joins)

In [121]:
df2 <- data.frame(k = seq(from = 20, to = 1, by = -1), l = runif(20))

In [122]:
nrow(df2); nrow(df);  seq(from = 20, to = 1, by = -1)

[1] 20

[1] 20

[1] 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1

In [123]:
merge(df,df2, by.x = "column1", by.y = "k" )

column1 y           z  l         
1   1      -0.14628418  2 0.67287964
2   2       0.05325144  4 0.96453983
3   3      -0.94819437  6 0.85706713
4   4      -1.95321281  8 0.24128071
5   5      -0.45413154 10 0.16332184
6   6       0.33389572 12 0.81732764
7   7      -0.32809396 14 0.96939337
8   8      -0.48890386 16 0.19250214
9   9      -0.38527410 18 0.01372898
10 10       0.12631490 20 0.89202829
11 11       0.31822365 22 0.50281488
12 12       0.63948067 24 0.63723423
13 13       0.40187661 26 0.34306957
14 14      -0.44545510 28 0.49967585
15 15      -1.24935889 30 0.69685599
16 16       0.08808607 32 0.72821074
17 17       0.91141631 34 0.71388098
18 18      -1.06872109 36 0.59140723
19 19       2.23029768 38 0.68063684
20 20      -1.47660927 40 0.94146582

Continuous data can be converted to categorical data by binning (conversion into pre-defined ranges or bins) using the cut() function

In [124]:
cut(df$y, c(-Inf,seq(0.5, 1, 0.1), Inf))

[1] (-Inf,0.5] (-Inf,0.5] (-Inf,0.5] (-Inf,0.5] (-Inf,0.5] (-Inf,0.5]
 [7] (-Inf,0.5] (-Inf,0.5] (-Inf,0.5] (-Inf,0.5] (-Inf,0.5] (0.6,0.7] 
[13] (-Inf,0.5] (-Inf,0.5] (-Inf,0.5] (-Inf,0.5] (0.9,1]    (-Inf,0.5]
[19] (1, Inf]   (-Inf,0.5]
7 Levels: (-Inf,0.5] (0.5,0.6] (0.6,0.7] (0.7,0.8] (0.8,0.9] ... (1, Inf]

### Apply function
A number of R programs require looping through a data frame and performing an operation on each record. The “apply” class of functions provide a short-cut through which that entire operation can be performed in one function call.

The function to apply for each row can by user defined function too.

Variants of the “apply” functions include apply, by, eapply, lapply, mapply, rapply, tapply

In [125]:
mat <- matrix(c(1:20), nrow= 10, ncol= 2)
apply(mat, 1, mean)
apply(mat, 2, mean)

[1]  6  7  8  9 10 11 12 13 14 15

[1]  5.5 15.5

apply(matrice, indice, funzione)
◮ con indice=1 applica funzione() alle righe di
matrice, e
◮ ritorna un vettore lungo come il numero di colonne.

In [126]:
nrighe <- 100000; ncolonne <- 10
m <- matrix(rnorm(nrighe*ncolonne),
nrow=nrighe, ncol=ncolonne)
mediacolonne <- apply(m,2,mean)

lapply(lista, funzione)
◮ Applica funzione() a ciascun elemento di lista;
◮ ritorna una list con la stessa lunghezza di lista.

In [127]:
L <- list(1:2, 3:7, -1:10)
lapply(L, sd)

[[1]]
[1] 0.7071068

[[2]]
[1] 1.581139

[[3]]
[1] 3.605551

sapply(dataframe, funzione)
◮ a ciascuna colonna di dataframe viene applicata
funzione();
◮ ritorna vettore lungo quanto il numero di colonne di
dataframe.

In [128]:
clienti <- data.frame(genere = c("M","F","F",NA),
altezza=c(172,186.5,165,180),
peso = c(91, 75, 74, 85))
sapply(clienti, mean)
sapply(clienti[ ,c(2,3)], quantile, prob=0.95)

Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"

genere altezza    peso 
     NA 175.875  81.250

altezza.95%    peso.95% 
    185.525      90.100

tapply(vettore, fattore, funzione)
◮ vettore viene suddiviso in sotto-vettori corrispondenti
alle fattore;
◮ a ciascun sottovettore viene applicata funzione();
◮ ritorna vettore lungo quanto il numero livelli di fattore.

In [129]:
clienti <- data.frame(genere = c("M","F","F",NA),
altezza=c(172,186.5,165,180),
peso = c(91, 75, 74, 85))
tapply(clienti$altezza, clienti$genere,
mean, na.rm=TRUE)

F      M 
175.75 172.00

# Control Structures

If-else:

`if (cond) expr`
`if (cond) expr1 else expr2`

For:

`for (varinseq) expr`

While:

`while (cond) expr`

Switch

Ifelse

`ifelse(test,yes,no)`

# User Defined Functions

Functions can be built and saved as function definitions in memory. They take input parameters and write output


In [130]:
computeSum <- function(x,y) {
    x+y
}

computeSum(3,5)

[1] 8

In [131]:
segno <- function(x){ 
    
    if(x<0){ 
        print("negativo") 
    }
    
    else { 
        print("non negativo") 
    }
    
} 

segno(0) # chiamata di funzione

[1] "non negativo"


In [132]:
funz <- function ( x, y = 2, z = 3 ) {
    return(x+y+z) 
}

funz(5)

[1] 10

## Data Clensing and Data Transformation
Issues with Data Quality

- Invalid values
- formats
- Attribute dependencies
- Uniqueness
- Referential integrity
- Missing values
- Misspellings
- Misfielded values (value in the wrong field)
- Wrong references

Finding Data Quality Issues

- Sample Visual Inspection
- Automated validation code
- Schema validation
- Outlier Analysis
- Exploratory Data Analysis

Fixing Data Quality Issues

- Fixing Data Quality issues is regular boilerplate coding in any language the team is comfortable with
- Fix the source if possible
- Find possible loopholes in data processing streams
- Analyze batches coming in and automate fixing
- Libraries and tools available

Data Imputation

- Any “value” present in a dataset is used by machine learning algorithms as valid values –including null, N/A, blank etc.
- This makes populating missing data a key step that might affect prediction results
- Techniques for populating missing data
- Mean, median, mode
- Multiple imputation
- Use regression to find values based on other values
- hybrid

Data Standardization

Numbers
- Decimal places
- Log
Date and Time
- Time Zone
- POSIX
- Epoch
Text Data
- Name formatting ( First Last vs Last, First)
- Lower case/ Upper case/ Init Case

Binning

- Convert numeric to categorical data
- Pre-defined ranges are used to create bins and individual data records are classified based on this.
- New columns typically added to hold the binned data
- Binning is usually done when the continuous variable is used for classification.

Indicator variables
- Categorical variables are converted into Boolean data by creating indicator variables
- If the variable has n classes, then n-1 new variables are created to indicate the presence or absence of a value
- Each variable has 1/0 values
- The nth value is indicated by a 0 in all the indicator columns
- Indicator variables sometimes work better in predictions that their categorical counterparts

Centering and Scaling
- Standardizes the range of values of a variables while maintaining their signal characteristics
- Makes comparison of two variables easier
- The values are “centered” by subtracting them from the mean value
- The values are “scaled” by dividing the above by the Standard Deviation.
- ML algorithms give far better results with standardized values